
#source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'EFNetworkDemo' do
 
pod 'Alamofire'
pod 'EFCore', :path => '../../tbbz-core'
end

target 'EFNetworkDemoUITests'  do
 
pod 'Alamofire'
pod 'EFCore', :path => '../../tbbz-core'
end
